project_name: easy-gate

env:
  - CGO_ENABLED=0

builds:
  - main: ./cmd/easy-gate/
    binary: easy-gate
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - "^MERGE"
      - "{{ .Tag }}"

release:
  github:
    owner: r7wx
    name: easy-gate
